

version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /data/mysql:/var/lib/mysql
    labels:
      important: "true"
    restart: always
    networks:
      - mynetwork

  adminer:
    image: adminer
    ports:
      - "8090:8080"
    networks:
    - mynetwork

  nestjs-app:
    build: ./backend/nodejs/nest-blog
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_DATABASE: blog
    restart: always
    networks:
      - mynetwork
    depends_on:
      - mysql

  # redis:
  #   image: redis:latest
  #   container_name: myredis
  #   ports:
  #     - "6379:6379"
  #   # 如果需要设置密码，可以使用下面的 command 选项：
  #   command: redis-server --requirepass 123456
  #   labels:
  #     important: "true"
  #   networks:
  #     - mynetwork

  # java_app:
  #   build:
  #     context: ./backend
  #   environment:
  #     - SERVICE_HOST=${SERVICE_HOST}
  #   ports:
  #     - "8081:8888"
  #   volumes:
  #     - /home/ec2-user/app/images:/app/images
  #   depends_on:
  #     - db
  #     - redis

  ssr:
    build:
      context: ./ssr/standalone
    restart: always
    environment:
      DOCKER_SERVER_HOST: https://kenjiding.com
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    # 设置nginx写入权限
    command: /bin/sh -c "mkdir -p /app/logs && chmod -R 755 /app/logs && nginx -g 'daemon off;'"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssr/standalone/.next/static:/app/ssr/standalone/.next/static
      - ./ssr/standalone/public:/app/ssr/standalone/public
      - ./logs:/app/logs
      - ./nginx/ssl:/etc/nginx/ssl
    restart: always
    networks:
    - mynetwork

networks:
  mynetwork:
